name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest


    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

        
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Cache Cypress binary
      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Cypress binary (if missing)
      - name: Install Cypress binary
        run: npx cypress install

      # Run Cypress Tests for adactinspec.cy.js
      - name: Run Cypress Tests - Adactin Spec 
        run: npx cypress run --spec cypress/e2e/adactinspec.cy.js --browser electron

      # Run Cypress Tests for loginspec.cy.js
      - name: Run Cypress Tests - Login Spec
        run: npx cypress run --spec cypress/e2e/loginspec.cy.js --browser electron

      # Upload Cypress Results
      - name: Upload Cypress Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos